#!/usr/bin/env bash
 
if [[ $# -eq 1 ]]; then
	selected_pretty=$1
else
	selected_pretty=$(printf "$(find ~/projects ~/.dotfiles -mindepth 1 -maxdepth 1 \( -name '.*' -o -name 'node_modules' \) -prune -o -type d -print )\n$HOME/.dotfiles" | sed "s|^/Users/$USER/|~/|" | \
		fzf  --preview 'ls -AFh --color $(echo {} | sed "s|^~/|/Users/$USER/|") | bat --color=always --theme=OneHalfDark' --height=100% --padding=2 --border=double --prompt='➤ ' --pointer='→' --preview-label='⟨ Directory Contents ⟩' --header='Tmux Sessionizer' --header-first --color='fg:magenta'
	)
fi

if [[ -z $selected_pretty ]]; then
	exit 0
fi

selected=$(echo $selected_pretty | sed "s|^~/|/Users/$USER/|")
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]]; then
	if [[ -z $tmux_running ]]; then
		tmux new-session -s $selected_name -c $selected

	elif tmux has-session -t=$selected_name 2> /dev/null; then
		tmux attach -t $selected_name
	
	elif ! tmux has-session -t=$selected_name 2> /dev/null; then
		tmux new -s $selected_name -c $selected
	fi

	exit 0
fi


if ! tmux has-session -t=$selected_name 2> /dev/null; then
	tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

