#!/usr/bin/env bash
 
read -p "Enter Project Name:" new_proj
if [[ -z $new_proj ]]; then
	exit 0
fi

proj_fp="$HOME/projects/$new_proj"
mkdir $proj_fp

selected_name=$(basename "$proj_fp" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]]; then
	if [[ -z $tmux_running ]]; then
		tmux new-session -s $selected_name -c $proj_fp

	elif tmux has-session -t=$proj_fp 2> /dev/null; then
		tmux attach -t $proj_fp
	
	elif ! tmux has-session -t=$selected_name 2> /dev/null; then
		tmux new -s $selected_name -c $proj_fp
	fi

	exit 0
fi


if ! tmux has-session -t=$selected_name 2> /dev/null; then
	tmux new-session -ds $selected_name -c $proj_fp
fi

tmux switch-client -t $selected_name

