#!/usr/bin/env bash
 # | sed "s|^/Users/[^/]*/|~/|" |
 # $(echo {} | sed "s|^~|$HOME|")
 
if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(printf "$(find ~/projects ~/.dotfiles -mindepth 1 -maxdepth 1 -type d | grep -v '/\.[^/]*$')\n/Users/jitalian/.dotfiles" | \
		fzf  --preview 'ls -AFh --color | bat --style=grid' --height=75% --margin=10%,5%,5%,10% --padding=2 --border=double --prompt='➤ ' --pointer='→' --preview-label='⟨ Directory Contents ⟩' --header='Tmux Sessionizer' --header-first --color='fg:magenta'
	)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]]; then
	if [[ -z $tmux_running ]]; then
		tmux new-session -s $selected_name -c $selected

	elif tmux has-session -t=$selected_name 2> /dev/null; then
		tmux attach -t $selected_name
	
	elif ! tmux has-session -t=$selected_name 2> /dev/null; then
		tmux new -s $selected_name -c $selected
	fi

	exit 0
fi


if ! tmux has-session -t=$selected_name 2> /dev/null; then
	tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

